### ISSUE TITLE
Option to open detached

### ISSUE THREAD

**Issue by andydandy74** [andydandy74/DynamoAutomation#16]
Need to explore if this is possible without user interaction, but it should be...

**Comment by denerlich** [comment]
Andy, good afternoon
since last post, the following workflow looks as a feasible way forward in handling central files via dynamo automation:
1: files can stay central, they just shall have no interruptions ( such as: unloadable links, prompts to open user selected worksets, permission issues etc.), File also ( in my case) shall preserve worksets, so it cannot be saved as "detached" as it will lose worksets. 
following C# macro ( courtesy  Metha Rajesh from Revit API forum http://forums.autodesk.com/t5/revit-api-forum/macro-open-document-as-detach-from-central-and-save-the-document/m-p/6795081#M20365)) 
creates "almost) autmatically the necessary New Central Files that can be batch processed.
----------------------------------------------------

/*
 * Created by SharpDevelop.
 * User: USER
 * Date: 1/11/2017
 * Time: 2:27 PM
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Autodesk.Revit.UI;
using Autodesk.Revit.DB;
using Autodesk.Revit.ApplicationServices;
using System.Windows.Forms;
using Autodesk.Revit;
using System.IO;

namespace Batch_Central_detach
{
    [Autodesk.Revit.Attributes.Transaction(Autodesk.Revit.Attributes.TransactionMode.Manual)]
    [Autodesk.Revit.DB.Macros.AddInId("60EED552-FB1F-4B02-B346-7C3C5046425F")]
	public partial class ThisApplication
	{
        private void Module_Startup(object sender, EventArgs e)
        {

        }

        private void Module_Shutdown(object sender, EventArgs e)
        {

        }

        #region Revit Macros generated code
        private void InternalStartup()
        {
            this.Startup += new System.EventHandler(Module_Startup);
            this.Shutdown += new System.EventHandler(Module_Shutdown);
        }
        #endregion
        public void savenotworkshared()
        {
            
            
OpenFileDialog theDialogRevit = new OpenFileDialog();
theDialogRevit.Title = "Select Revit Project Files";
theDialogRevit.Filter = "RVT files|*.rvt";
theDialogRevit.FilterIndex = 1;
theDialogRevit.InitialDirectory = @"C:\";
theDialogRevit.Multiselect = true;
if (theDialogRevit.ShowDialog() == DialogResult.OK)    
            
    {             
 string mpath = "";
        string mpathOnlyFilename = "";
        FolderBrowserDialog folderBrowserDialog1 = new FolderBrowserDialog();
        folderBrowserDialog1.Description = "Select Folder Where Revit Projects to be Saved in Local";
        folderBrowserDialog1.RootFolder = Environment.SpecialFolder.MyComputer;
        if (folderBrowserDialog1.ShowDialog() == DialogResult.OK)
        {
         mpath = folderBrowserDialog1.SelectedPath;
                foreach (String projectPath in theDialogRevit.FileNames)
                {
                 FileInfo filePath = new FileInfo(projectPath);
                        ModelPath mp = ModelPathUtils.ConvertUserVisiblePathToModelPath(filePath.FullName);
                        OpenOptions opt = new OpenOptions();
                        
                        opt.DetachFromCentralOption = DetachFromCentralOption.DetachAndPreserveWorksets;
                        mpathOnlyFilename = filePath.Name;
                        Document openedDoc = Application.OpenDocumentFile(mp, opt);                               
                        SaveAsOptions options = new SaveAsOptions();
                        options.OverwriteExistingFile = true;
                        WorksharingSaveAsOptions wsOptions = new WorksharingSaveAsOptions();
                        wsOptions.OpenWorksetsDefault = SimpleWorksetConfiguration.AllEditable;
                        wsOptions.SaveAsCentral = true;
   						options.SetWorksharingOptions( wsOptions );
                        ModelPath modelPathout = ModelPathUtils.ConvertUserVisiblePathToModelPath(mpath + "\\" + mpathOnlyFilename);
                        openedDoc.SaveAs(modelPathout, options);
                        openedDoc.Close(false);
               }
        }
}
        }
	}
}
----------------------------------

still work in progress, as code does not unload revit links and do not handle interruptions, but it is almost there.

I assume that the responsible node that shall handle opening and closing Revit file with mentioned options shall be part of Master graph, as it is master graph that evokes and closes Revit transaction...

**Comment by andydandy74** [comment]
This would be done via the journal itself

**Comment by andydandy74** [comment]
Now tracked in #29

**Comment by andydandy74** [comment]
We'll need these two commands to make it work:
```
Jrn.Data "FileOpenSubDialog" , "OpenAsLocalCheckBox", "False"
Jrn.Data "FileOpenSubDialog"  , "DetachCheckBox", "True"
```

**Comment by andydandy74** [comment]
Let's try this more complete version next:
```
Jrn.Data "FileOpenSubDialog"  , "DetachCheckBox", "True"
Jrn.Data "File Name" , "IDOK", "{MODELPATH}.rvt"
Jrn.Data "WorksetConfig" , "Custom", 0
```
And after that:
```
Jrn.Data "TaskDialogResult" , "Detaching this model will create an independent model. You will be unable to synchronize your changes with the original central model." & vbLf & "What do you want to do?", "Detach and discard worksets", "1002"
```
Alternatively:
```
Jrn.Data "TaskDialogResult" , "Detaching this model will create an independent model. You will be unable to synchronize your changes with the original central model." & vbLf & "What do you want to do?", "Detach and preserve worksets", "1001"

**Comment by andydandy74** [comment]
@denerlich - Option to detach model from central on open will be available in the next release.
