### ISSUE TITLE
Journal.ByWorkspacePath cannot take arguments of type

### ISSUE THREAD

**Issue by milotindragos** [andydandy74/DynamoAutomation#39]
### Description
The Node Journal.ByWorkspacePath is fgivint a errror of cannot take arguments of type(__array,System.IO.FileInfo,__array,string).

Revit is launching but it does not do anything. I am using the examples setup and did not change anything from the presets. 

### My setup
- Operating System: Windows 10
- Dynamo version: 1.3.1.1736
- Revit version & build number: Revit 2017.2

![2017-08-18_04-25-16](https://user-images.githubusercontent.com/30367360/29443242-a0a30e04-83ce-11e7-8b69-a276cbf1a7e9.png)
![2017-08-18_04-34-05](https://user-images.githubusercontent.com/30367360/29443240-a0a23c36-83ce-11e7-8a75-18d32303fc67.png)
![2017-08-18_04-34-21](https://user-images.githubusercontent.com/30367360/29443241-a0a2d6b4-83ce-11e7-946a-13e9005fdac0.png)

**Comment by andydandy74** [comment]
Looking at your screenshot of the Journal.ByWorkspacePath node, I can see you are using an old version of DynamoAutomation that will not run with Revit 2017. Please upgrade.

**Comment by milotindragos** [comment]
Hey. I am using the one that can be found and installed via the package manager and I also downloaded the one from here and tested out. Where can I find a new-er version? 

I tested these 2:
![2017-08-18_09-23-42](https://user-images.githubusercontent.com/30367360/29450559-0e0c5dd8-83f7-11e7-8d24-df6a071efad1.png)

**Comment by andydandy74** [comment]
Looking at what you wrote in issue #38 it looks like you are using the DLL from DA 1.3.2 - the Journal.ByWorkspacePath node from DA 1.3.3 has an additional input. Apart from the package manager, you can get the latest version here on GitHub (without the JSON package file).
The best way to do that is to clone or download the entire repo:
![grafik](https://user-images.githubusercontent.com/3014437/29451171-f5654d48-8401-11e7-9cae-dcac99c1d895.png)
I am doubtful, however, if that will solve issue #38 which is what I am focusing on right now. Once that issue is solved and you have the latest version of DA installed and your problem persists, please open a new issue. Please understand that I do not have the time to investigate issues not based on the latest build of the package.

**Comment by milotindragos** [comment]
Ok I fully understand not investigeting back issues. I have downloaded the latest version from here but now I have issue #38. That is the original issue and I was trying to avoid it. I will wait for that one to be fixed then. 
Thanks

**Comment by andydandy74** [comment]
Incidentally, I thought about your particular error message again during lunch break. Do you by any chance pass the workspace filepath through a File From Path node? That would explain why it says ```System.IO.File``` in your erros message.

**Comment by milotindragos** [comment]
I only installed DynamoAutomation yesterday for the first time and I did not change the default example. They are exactly as you have them in the samples folder and saved to C:\temp\DynamoAutomation.

**Comment by andydandy74** [comment]
Weird
